name: Auto Sign

on:
  schedule:
    - cron: '0 2 * * *' # 每天 0 点触发
  workflow_dispatch: # 手动触发器
  push:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: 'signs'
        run: node index.js
        env:
          RUIKE_COOKIE: ${{ secrets.RUIKE_COOKIE }}
          V2EX_COOKIE: ${{secrets.V2EX_COOKIE}}
