name: Auto Sign

on:
  schedule:
    - cron: '0 0 * * *' # 每天 0 点触发
  workflow_dispatch: # 手动触发器

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run sign.js
        run: node sign.js
        env:
          COOKIE: ${{ secrets.COOKIE }} # 使用 COOKIE Secret
