name: Auto Sign

on:
  schedule:
    - cron: '0 2 * * *' # 每天 0 点触发
  workflow_dispatch: # 手动触发器
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: |
          go get -u github.com/chromedp/chromedp

      - name: Run Chrome Headless Sign In
        run: |
          go run main.go USERNAME PASSWORD
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
